### ISSUE TITLE
About static information

### ISSUE THREAD

**Issue by Tommybro** [SWPP/ttrs-backend#79]
At `ttrs/static-information/`
`fields` should be array not object.
please remove `colleges` and `semesters`. They makes front slow when get response

**Comment by holenet** [comment]
### fields
`fields` can be either an array or an object.
But, additional key names are needed when choose to represent `fields` as array.

**e.g.**
```json
[
  {
    "name": "학문의 세계",
    "details": [
      "역사와 철학",
      "정치와 경제",
      "문화와 예술",
      "자연과 기술",
      "언어와 문학",
      "인간과 사회"
     ]
  },
  ...
]
```

`name` and `details` are indispensable.
So, I decided to use object(i.e. dictionary).

**P.S.** You can convert keys of js object to array by using a function `Object.keys`

### colleges & semesters
I don't think these are slowing down the speed of responses.
According to my benchmark, the most part of the time consumption was because of fields and types and semesters.
colleges consumes lower than 20%.
And, semesters are needed to calculated before making fields and types.

If you have more questions, feel free to reply to me.

**Comment by holenet** [comment]
Closing with #80
